#!/usr/bin/env bash
#solve what’s keeping my Ubuntu container’s Nginx
#installation from listening on port 80.😮‍💨

# Remove the default symbolic link if it exists
sudo rm /etc/nginx/sites-enabled/default
#create symbolic link from the Nginx sites-available config to sites-enabled
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
sudo service nginx start
