#! /usr/bin/env bash
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
sudo ufw status
sudo ufw route allow proto tcp from any to any port 8080
sudo ufw route allow proto tcp from any to any port 80
sudo ufw reload
sudo ufw status
